name: Daily Diagnostic Check
on:
  schedule:
    # Run daily at 6:30 AM EDT (10:30 AM UTC)
    - cron: '30 10 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Run diagnostic check
        id: diagnostic
        run: |
          python diagnostic_check.py 2>&1 | tee diagnostic_output.log
        continue-on-error: true
      
      - name: Check for major failures
        id: check_failures
        run: |
          if grep -E "(FAIL.*card|FAIL.*map|FAIL.*link|FAIL.*color)" diagnostic_output.log; then
            echo "major_failure=true" >> $GITHUB_OUTPUT
            echo "::error::Major diagnostic check failures detected (cards, map, links, or color logic)"
          else
            echo "major_failure=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload diagnostic artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diagnostic-report-${{ github.run_number }}
          path: diagnostic_output.log
          retention-days: 30
      
      - name: Notify on major failure
        if: steps.check_failures.outputs.major_failure == 'true'
        run: |
          echo "::error::Daily diagnostic check found major issues. Please review the artifact and logs."
          exit 1
