name: Daily Diagnostic Check

on:
  schedule:
    # Run daily at 8:00 AM UTC (4:00 AM EDT / 3:00 AM EST)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Run diagnostic check
        run: |
          python diagnostic_check.py
      
      - name: Report status
        if: failure()
        run: |
          echo "::error::Diagnostic check failed. Review the logs above for details."
